blank_issues_enabled: false
contact_links:
  - name: Search the Docs | 搜索文档
    url: https://kookybot.rtfd.io
    about: Refer to the docs and search for what you are looking for. | 参考文档并搜索您所需的内容。
  - name: Search or ask in KOOK Server | 在 KOOK 服务器中搜索或提问
    url: https://kook.top/wnWOP9
  - name: Problems about the documentation | 关于文档的问题
    url: https://github.com/KookyBot/KookyBot-Docs/issues
    about: Open an issue in the documentation repository. | 在文档仓库中提交 issue。
